In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    'k1':['a','b','a','a','c','c','b','a','c','a','b','c'],
    'k2':['one','two','three','two','one','one','three','one','two','three','one','two'],
    'w':np.random.rand(12),
    'y':np.random.randn(12)    
})
df

   k1     k2         w         y
0   a    one  0.261745 -0.448976
1   b    two  0.568532  1.021547
2   a  three  0.270610  0.980371
3   a    two  0.558682 -0.501370
4   c    one  0.724952  1.062792
5   c    one  0.824911  0.472453
6   b  three  0.082029  1.918419
7   a    one  0.607809  1.882542
8   c    two  0.837026 -1.651458
9   a  three  0.490608  0.289954
10  b    one  0.291842 -0.533895
11  c    two  0.855648 -0.676939

In [ ]:
#  使用pivot_table方法创建数据透视表 index参数指定行索引
# 这里使用'k1'列作为行索引 columns参数指定列索引
# 这里使用'k2'列作为列索引 aggfunc参数指定聚合函数
# 这里使用求和函数"sum"对数据进行汇总
df.pivot_table(index='k1',columns='k2', aggfunc="sum")

In [6]:
df.pivot_table(index='k1',columns='k2', value="w")

TypeError: DataFrame.pivot_table() got an unexpected keyword argument 'value'. Did you mean 'values'?

In [ ]:
# 使用pandas库中的crosstab函数创建交叉表
# 交叉表是一种用于分析分类变量之间关系的表格
# 参数df.k1和df.k2分别表示DataFrame中的两列分类数据
pd.crosstab(df.k1,df.k2)

k2  one  three  two
k1
a     2      2    1
b     1      1    1
c     2      0    2

In [7]:
pd.crosstab(df.k1,df.k2, margins=True)

k2   one  three  two  All
k1
a      2      2    1    5
b      1      1    1    3
c      2      0    2    4
All    5      3    4   12