In [96]:
import pandas as pd
# 导入pandas库并创建一个DataFrame对象
df = pd.DataFrame({'one_name': [1, 2, 3], 'two_name': [4, 5, 6]})  # 使用字典创建DataFrame，键作为列名，值作为数据
df  # 输出DataFrame对象，展示其内容

   one_name  two_name
0         1         4
1         2         5
2         3         6

In [12]:
# 不带索引
df.to_csv('data.csv', index=False)

In [14]:
# 带索引
df.to_csv('data.csv', index=True)

In [ ]:
# 使用pandas库读取CSV文件
# pd是pandas库的常用别名，通过这个别名可以调用pandas库的各种功能
# read_csv()是pandas库中用于读取CSV文件的函数
# 'data.csv'是要读取的CSV文件名，这里假设文件与当前脚本在同一目录下
pd.read_csv('data.csv')

   Unnamed: 0  one_name  two_name
0           0         1         4
1           1         2         5
2           2         3         6

读写Excel文件

In [18]:
df = pd.DataFrame({'col1': ['广','东'], 'col2': ['培','正'],'col3': ['学','院']})
df

  col1 col2 col3
0    广    培    学
1    东    正    院

In [27]:
df.to_excel('data.xlsx', sheet_name="花都", index=False)
df

  col1 col2 col3
0    广    培    学
1    东    正    院

In [29]:
pd.read_excel('data.xlsx', sheet_name="花都")

  col1 col2 col3
0    广    培    学
1    东    正    院

# 读取html表格数据

In [ ]:
import requests
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
}
res = requests.get('https://www.tianqihoubao.com/aqi/chengdu-201901.html', headers=headers)
print(res.status_code)
# print(res.text)

pd.read_html(res.text)

200

C:\Users\yandifei\AppData\Local\Temp\ipykernel_24588\1253518290.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(res.text)

[             0      1     2        3      4     5    6    7     8   9
 0           日期  AQI指数  质量等级  当天AQI排名  PM2.5  PM10  No2  So2    Co  O3
 1   2019-01-01     68     良      186     49    67   43    7  1.07  19
 2   2019-01-02     80     良      179     58    84   41    8  0.94  24
 3   2019-01-03     86     良      177     63    92   42    6  0.89  17
 4   2019-01-04     71     良      175     51    87   44    5  0.90  35
 5   2019-01-05     89     良      246     65   106   55    7  1.15  36
 6   2019-01-06    113  轻度污染      263     84   131   57    7  1.08  23
 7   2019-01-07    110  轻度污染      241     82   120   51    7  1.07  29
 8   2019-01-08    119  轻度污染      276     89   139   62   10  1.25  22
 9   2019-01-09    120  轻度污染      331     90   129   50    8  1.02  27
 10  2019-01-10     89     良      239     65    90   38    5  1.05  23
 11  2019-01-11     85     良      194     62    88   46    6  1.24  35
 12  2019-01-12     97     良      210     72   104   56    6  1.32  22
 13  2019-01-13     91     良      165     67   100   45    7  1.29  35
 14  2019-01-14    125  轻度污染      219     94   139   62    9  1.46  27
 15  2019-01-15     70     良      166     45    77   43    6  0.79  41
 16  2019-01-16     80     良      270     56    96   46    7  0.67  39
 17  2019-01-17    111  轻度污染      319     82   132   55    8  0.86  24
 18  2019-01-18     94     良      208     70   106   45    5  0.82  30
 19  2019-01-19     78     良      159     56    91   46    7  0.87  43
 20  2019-01-20     81     良      220     58   106   52    8  0.89  48
 21  2019-01-21     61     良      135     38    70   45    6  0.59  41
 22  2019-01-22     93     良      227     68   109   50    9  0.78  37
 23  2019-01-23    124  轻度污染      305     93   148   61   11  0.99  39
 24  2019-01-24    121  轻度污染      247     91   143   63    9  0.93  30
 25  2019-01-25    136  轻度污染      291    103   154   59    9  1.03  32
 26  2019-01-26    136  轻度污染      312    103   148   49    8  1.07  29
 27  2019-01-27     83     良      203     60    85   29    4  0.92  28
 28  2019-01-28     73     良      165     52    75   33    5  0.94  48
 29  2019-01-29     97     良      216     72   101   41    5  1.00  40
 30  2019-01-30     95     良      221     70    98   41    5  0.97  31
 31  2019-01-31     80     良      310     58    86   38    5  0.99  27]

# 数据库

In [23]:
from sqlalchemy import create_engine

In [38]:
engine = create_engine('mysql+mysqlconnector://root:yandifei@localhost:3306/test')
pd.read_sql("user_info", engine)

   id username  age gender              email         create_time
0   1       张三   22      男  zhangsan@test.com 2026-04-16 09:25:03
1   2       李四   25      女      lisi@test.com 2026-04-16 09:25:03
2   3       王五   28      男    wangwu@test.com 2026-04-16 09:25:03
3   4       赵六   21      女   zhaoliu@test.com 2026-04-16 09:25:03
4   5       钱七   30      男    qianqi@test.com 2026-04-16 09:25:03

In [ ]:
pd.read_sql("SELECT * FROM test.user_info where age>25;", engine)

   id username  age gender            email         create_time
0   3       王五   28      男  wangwu@test.com 2026-04-16 09:25:03
1   5       钱七   30      男  qianqi@test.com 2026-04-16 09:25:03

In [37]:
# 写入数据库
df = pd.DataFrame({"班级":["一年级","二年级","三年级","四年级"],
                              "男生人数":[25,23,27,30],
                              "女生人数":[19,17,20,20]})
df

    班级  男生人数  女生人数
0  一年级    25    19
1  二年级    23    17
2  三年级    27    20
3  四年级    30    20

In [41]:
df.to_sql("students", engine)

4

    案例—读取北京市2006~2018年高考分数线表格信息及分析
    1.读取一二本各科最高和最低分数线
    2.求出最高分与最低分之差
    3.求出2018年与2017年各科的分数变化
    4.求出常用的计算量

In [ ]:
data = pd.read_excel("scores.xlsx", header=[0, 1], index_col=0)
# data.columns = ["文科"]
data

     一本分数线      二本分数线
        文科   理科    文科   理科
2018   576  532   488  432
2017   555  537   468  439
2016   583  548   532  494
2015   579  548   527  495
2014   565  543   507  495
2013   549  550   494  505
2012   495  477   446  433
2011   524  484   481  435
2010   524  494   474  441
2009   532  501   489  459
2008   515  502   472  455
2007   528  531   489  478
2006   516  528   476  476

In [66]:
# 预览数据结构（确保列名包含：年份、科类、批次、分数线等）
print(data.head())

     一本分数线      二本分数线
        文科   理科    文科   理科
2018   576  532   488  432
2017   555  537   468  439
2016   583  548   532  494
2015   579  548   527  495
2014   565  543   507  495

In [72]:
# 最大值
data.max()

一本分数线  文科    583
       理科    550
二本分数线  文科    532
       理科    505
dtype: int64

In [ ]:
# --- 读取一二本各科最高和最低分数线 ---
# 过滤出一本和二本的数据
data.max() - data.min()

一本分数线  文科    88
       理科    73
二本分数线  文科    86
       理科    73
dtype: int64

In [83]:
# --- 任务 3：求出2018年与2017年各科的分数变化 ---
# 筛选出这两年的数据
data["一本分数线", "文科"] - data["一本分数线", "文科"]

2018    0
2017    0
2016    0
2015    0
2014    0
2013    0
2012    0
2011    0
2010    0
2009    0
2008    0
2007    0
2006    0
Name: (一本分数线, 文科), dtype: int64

In [85]:
data.describe()

            一本分数线                   二本分数线
               文科          理科          文科          理科
count   13.000000   13.000000   13.000000   13.000000
mean   541.615385  521.153846  487.923077  464.384615
std     28.150010   25.986683   23.567144   27.274953
min    495.000000  477.000000  446.000000  432.000000
25%    524.000000  501.000000  474.000000  439.000000
50%    532.000000  531.000000  488.000000  459.000000
75%    565.000000  543.000000  494.000000  494.000000
max    583.000000  550.000000  532.000000  505.000000

# 数据清洗
## 空值和缺失值的处理

In [ ]:
from numpy import nan
ser_obj = pd.Series([1, None, nan])
ser_obj

0    1.0
1    NaN
2    NaN
dtype: float64

In [97]:
pd.insnull(ser_obj)

AttributeError: module 'pandas' has no attribute 'insnull'

In [94]:
pd.notnull(ser_obj)

0     True
1    False
2    False
dtype: bool

In [100]:
import numpy as np
df_obj = pd.DataFrame({"类别":['小说', '散文随笔', '青春文学', '传记'],
                       "书名":[np.nan, '《皮囊》', '《旅程结束时》', '《老舍自传》'],
                       "作者":["老舍", None, "张其鑫", "老舍"]})
df_obj

     类别       书名    作者
0    小说      NaN    老舍
1  散文随笔     《皮囊》  None
2  青春文学  《旅程结束时》   张其鑫
3    传记   《老舍自传》    老舍

In [101]:
df_obj.dropna()

     类别       书名   作者
2  青春文学  《旅程结束时》  张其鑫
3    传记   《老舍自传》   老舍

In [ ]:
# 使用 fillna 方法填充 DataFrame 中的缺失值
# fillna() 是 pandas 中用于处理缺失值的方法
# 参数 "66" 表示将所有的缺失值（NaN）替换为字符串 "66"
df_obj.fillna("66")

     类别       书名   作者
0    小说       66   老舍
1  散文随笔     《皮囊》   66
2  青春文学  《旅程结束时》  张其鑫
3    传记   《老舍自传》   老舍

In [108]:
df_obj = pd.DataFrame({'A': [1, 2, 3, nan],
                       'B': [nan, 4, nan, 6],
                       'C': ['a', 7, 8, 9],
                       'D':[nan, 2, 3, nan]})
df_obj

     A    B  C    D
0  1.0  NaN  a  NaN
1  2.0  4.0  7  2.0
2  3.0  NaN  8  3.0
3  NaN  6.0  9  NaN

In [110]:
df_obj.fillna({"a":4, "B":5, "D":6})

     A    B  C    D
0  1.0  5.0  a  6.0
1  2.0  4.0  7  2.0
2  3.0  5.0  8  3.0
3  NaN  6.0  9  6.0

In [112]:
df_obj.fillna(method="ffill")

C:\Users\yandifei\AppData\Local\Temp\ipykernel_24588\3530654824.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_obj.fillna(method="ffill")

     A    B  C    D
0  1.0  NaN  a  NaN
1  2.0  4.0  7  2.0
2  3.0  4.0  8  3.0
3  3.0  6.0  9  3.0

In [113]:
df_obj.fillna(method="bfill")

C:\Users\yandifei\AppData\Local\Temp\ipykernel_24588\2291557249.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_obj.fillna(method="bfill")

     A    B  C    D
0  1.0  4.0  a  2.0
1  2.0  4.0  7  2.0
2  3.0  6.0  8  3.0
3  NaN  6.0  9  NaN

In [114]:
# 重复值

In [116]:
# 重复值的处理
person_info = pd.DataFrame({'id': [1, 2, 3, 4, 4, 5],
                            'name': ['小铭', '小月月', '彭岩', '刘华', '刘华', '周华'],
                            'age': [18, 18, 29, 58, 58, 36],
                            'height': [180, 180, 185, 175, 175, 178],
                            'gender': ['女', '女', '男', '男', '男', '男']})
person_info

   id name  age  height gender
0   1   小铭   18     180      女
1   2  小月月   18     180      女
2   3   彭岩   29     185      男
3   4   刘华   58     175      男
4   4   刘华   58     175      男
5   5   周华   36     178      男

In [117]:
person_info.duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [119]:
person_info.drop_duplicates()

   id name  age  height gender
0   1   小铭   18     180      女
1   2  小月月   18     180      女
2   3   彭岩   29     185      男
3   4   刘华   58     175      男
5   5   周华   36     178      男

In [ ]:
person_info.drop_duplicates(keep="last", inplace=True)